package commons;

import jakarta.persistence.*;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.jetbrains.annotations.NotNull;

import java.time.LocalDateTime;

import static org.apache.commons.lang3.builder.ToStringStyle.MULTI_LINE_STYLE;

/**
 * Note entity with title, content and creation date. Stored in database.
 */
@Entity
public class Note {

    /**
     * id acts as unique identifier for the note, auto-generated by db.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    /**
     * Title of the note. Cannot be null
     */
    @Column(nullable = false)
    @NotNull
    private String title;

    private String content;

//    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
//    private final LocalDateTime creationTime = LocalDateTime.now();

    public Note() {
        // for object mappers
    }

    /**
     * Creates a new note with a certain title and content and sets the creation time as the current time
     * @param title the title of the note
     * @param content the content of the note
     */
    public Note(String title, String content) {
        this.title = title;
        this.content = content;
    }

    /**
     * checks if two notes are equal
     * @param obj object to compare with
     * @return true if the notes are equal
     */
    @Override
    public boolean equals(Object obj){
        return EqualsBuilder.reflectionEquals(this, obj);
    }

    /**
     * Calculates the hash value
     * @return the hash value of the note
     */
    @Override
    public int hashCode(){
        return HashCodeBuilder.reflectionHashCode(this);
    }

    /**
     * Creates a string representation of the note
     * @return a string representation of the note
     */
    @Override
    public String toString(){
        //return ToStringBuilder.reflectionToString(this, MULTI_LINE_STYLE);
        String result = "\n" + title + "\n" + content + "\n";
        return result;
    }

    public long getId(){
        return id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

//    public LocalDateTime getCreationTime() {
//        return creationTime;
//    }
}
